### ISSUE TITLE
Splinter error in buoy_examples/torque_controller

### ISSUE THREAD

**Issue by hamilton8415** [osrf/buoy_examples#20]
Since the splinter inclusion, this doesn't build correctly for me, errors below, and maybe not obvious to me as to how to fix so I am listing it here.  I didn't see any branches with a likely change that would avoid this.  Not pressing for me as I don't need this repo to proceed...

--- stderr: buoy_examples                                                                           
CMake Error at CMakeLists.txt:16 (add_executable):
  Target "torque_controller" links to target "splinter_ros::splinter1d" but
  the target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?

CMake Error at CMakeLists.txt:16 (add_executable):
  Target "torque_controller" links to target "splinter_ros::splinter2d" but
  the target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?

CMake Generate step failed.  Build files cannot be regenerated correctly.

Failed   <<< buoy_examples [0.96s, exited with code 1]

**Comment by andermi** [comment]
Try `rm -rf build install` and a new terminal. also, remove the `src/buoy_examples` source directory

edit: I just noticed this issue is in the `buoy_examples` repo... don't use `buoy_examples` anymore. I'm going to remove the `buoy_examples` repo from `buoy_all.yaml` in `buoy_entrypoint`

all the content from `buoy_examples` has moved into `buoy_msgs` repo
